- name: install cron job for ansible pull
  cron:
    user: ansible
    name: "ansible"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/manprinsen/ansible-test001.git >> /var/log/ansible-pull.log 2>&1"